name: 'Extract version from tag'
description: 'Create multiple variables from the extracted tag version'
author: 'damienaicheh'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
